version: "4.19.0"

services:
  persistence:
    image: fileio-service
    build:
      context: ./fileIO/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    container_name: fileio_service
    environment:
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8080
    tty: true

  main:
    image: connect4-game
    build:
      context: ./
      dockerfile: ../Dockerfile
    stdin_open: true
    container_name: connect4_game
    depends_on:
      - persistence
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
      CONNECTFOUR_SERVICE_HOST: connectfour
      CONNECTFOUR_SERVICE_PORT: 8080
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8081