name: Scala CI

on:
  pull_request:
    branches: [ sa23-FINAL, software-architektur23(coveralls) ]
  push:
    branches: [ sa23-FINAL, software-architektur23(coveralls) ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: compile
      run: sbt compile
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Project and export Coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          export CI_BRANCH="${GITHUB_REF#refs/heads/}"
          sbt clean jacoco jacocoCoveralls

      - name: Run tests
        run: sbt clean coverage test

      - name: Upload coverage data to Coveralls
        run: sbt coverageReport coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_FLAG_NAME: WhatIsThis

      - name: Upload coverage data to Coveralls
        run: sbt coverageAggregate coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          COVERALLS_FLAG_NAME: WhatIsThis
