on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
   - name: Coveralls GitHub Action
  uses: coverallsapp/github-action@1.1.3
    with:
      github-token: ${{ secrets.REPO_TOKEN }}
